# Generated by Django 5.1.1 on 2024-11-06 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('especialidad_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Especialidad')),
                ('especialidad_nombre', models.CharField(max_length=50, verbose_name='Especialidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
                'ordering': ['especialidad_nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('historia_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Historia Clínica')),
                ('historia_fecha', models.DateTimeField(auto_now_add=True)),
                ('historia_descripcion', models.TextField(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Historias Clínicas',
                'ordering': ['historia_fecha'],
            },
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('insumo_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Insumo')),
                ('insumo_nombre', models.CharField(max_length=50, verbose_name='Nombre Insumo')),
                ('stock_actual', models.IntegerField(verbose_name='Stock Actual')),
                ('stock_minimo', models.IntegerField(verbose_name='Stock Mínimo')),
                ('unidad_medida', models.CharField(max_length=50, verbose_name='Unidad de Medida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Insumos',
                'ordering': ['insumo_nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProveedoresSeguros',
            fields=[
                ('proveedor_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Proveedor')),
                ('proveedor_nombre', models.CharField(max_length=50, verbose_name='Nombre Proveedor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedores de Seguros',
                'ordering': ['proveedor_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Admin')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('admin_password', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('admin_dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('admin_telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pictures')),
                ('status', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_joined', 'time'],
                'unique_together': {('date_joined', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('estudio_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Estudio')),
                ('estudio_nombre', models.CharField(max_length=50, verbose_name='Nombre Estudio')),
                ('estudio_descripcion', models.CharField(max_length=100, verbose_name='Descripción Estudio')),
                ('estudio_precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Estudio')),
                ('app_total', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especialidad', models.ForeignKey(default='Seleccione una opción', on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='coreadmin.especialidades')),
                ('insumos', models.ManyToManyField(blank=True, related_name='estudios', to='coreadmin.insumos')),
            ],
            options={
                'verbose_name_plural': 'Estudios',
                'ordering': ['estudio_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('paciente_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Paciente')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('phone', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pictures')),
                ('plan_seguro', models.CharField(max_length=50, verbose_name='Plan')),
                ('numero_asociado', models.CharField(max_length=20, unique=True, verbose_name='Número de Afiliado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('HistoriaClinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreadmin.historiaclinica')),
                ('proveedor_nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.proveedoresseguros')),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='IngresoPaciente',
            fields=[
                ('ingreso_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Visita')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha Visita')),
                ('ingreso_hora', models.TimeField(verbose_name='Hora Visita')),
                ('ingreso_tipo', models.CharField(choices=[('SIN_TURNO', 'Ingreso por Guardia'), ('CON_TURNO', 'Ingreso con Turno')], default='CON_TURNO', max_length=20)),
                ('ingreso_gravedad', models.CharField(blank=True, choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=10, null=True)),
                ('estado', models.CharField(choices=[('Esperando', 'Esperando'), ('En progreso', 'En progreso'), ('Completada', 'Completada')], max_length=20)),
                ('fecha_hora_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora Completado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('HistoriaClinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreadmin.historiaclinica')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.estudios')),
                ('insumos', models.ManyToManyField(related_name='appointments', to='coreadmin.insumos')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.paciente')),
            ],
            options={
                'verbose_name_plural': 'Ingreso',
                'ordering': ['fecha_ingreso'],
            },
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='paciente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.paciente'),
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingreso_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='coreadmin.ingresopaciente')),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('factura_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Factura')),
                ('factura_numero', models.IntegerField(unique=True, verbose_name='Número Factura')),
                ('factura_fecha', models.DateField(verbose_name='Fecha Factura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.paciente')),
                ('pago_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.pagos', verbose_name='ID Pago')),
            ],
            options={
                'verbose_name_plural': 'Facturas',
                'ordering': ['factura_numero'],
            },
        ),
        migrations.CreateModel(
            name='Profesionales',
            fields=[
                ('profesional_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Profesional')),
                ('profesional_nombre', models.CharField(max_length=50, verbose_name='Nombre Profesional')),
                ('profesional_apellido', models.CharField(max_length=50, verbose_name='Apellido Profesional')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pictures')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('especialidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.especialidades')),
            ],
            options={
                'verbose_name_plural': 'Profesionales',
                'ordering': ['profesional_apellido'],
            },
        ),
        migrations.AddField(
            model_name='ingresopaciente',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.profesionales'),
        ),
        migrations.AddField(
            model_name='estudios',
            name='profesional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='coreadmin.profesionales'),
        ),
        migrations.CreateModel(
            name='ResultadoLaboratorio',
            fields=[
                ('resultado_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Resultado')),
                ('resultado_detalle', models.CharField(max_length=200, verbose_name='Detalle Resultado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resultado_fecha', models.DateField(verbose_name='Fecha Resultado')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estudio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.estudios')),
                ('visita_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.ingresopaciente')),
            ],
            options={
                'verbose_name_plural': 'Resultados de Laboratorio',
                'ordering': ['resultado_fecha'],
            },
        ),
        migrations.CreateModel(
            name='SalaEspera',
            fields=[
                ('sala_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Sala')),
                ('sala_nombre', models.CharField(max_length=50, verbose_name='Nombre Sala')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('IngresoPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.ingresopaciente', verbose_name='Ingreso Paciente')),
                ('estudio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreadmin.estudios', verbose_name='Estudio')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreadmin.profesionales', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Sala de Espera',
                'verbose_name_plural': 'Salas de Espera',
            },
        ),
        migrations.CreateModel(
            name='SolicitudesInsumos',
            fields=[
                ('estado_solicitud', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Completada', 'Completada')], default='Pendiente', max_length=20)),
                ('solicitud_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Solicitud')),
                ('solicitud_fecha', models.DateField(verbose_name='Fecha Solicitud')),
                ('cantidad_solicitada', models.CharField(max_length=5, verbose_name='Cantidad Solicitada')),
                ('solicitado_por', models.CharField(max_length=50, verbose_name='Solicitado por')),
                ('fecha_completada', models.DateField(blank=True, null=True, verbose_name='Fecha Completada')),
                ('fecha_actualizacion', models.DateField(blank=True, null=True, verbose_name='Fecha Actualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insumo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.insumos')),
            ],
            options={
                'verbose_name_plural': 'Solicitudes de Insumos',
                'ordering': ['solicitud_fecha', 'estado_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programada'), ('CONFIRMED', 'Confirmada'), ('CHECKED_IN', 'Checked in'), ('CHECKED_OUT', 'Checked out'), ('CANCELLED', 'Cancelada')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='coreadmin.especialidades')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='coreadmin.estudios')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='coreadmin.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='coreadmin.profesionales')),
            ],
            options={
                'verbose_name_plural': 'Turnos',
                'ordering': ['date', 'time'],
                'unique_together': {('profesional', 'date', 'time')},
            },
        ),
        migrations.AddField(
            model_name='ingresopaciente',
            name='appointment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.turnos'),
        ),
        migrations.CreateModel(
            name='HistoriaClinicaDetalle',
            fields=[
                ('detalle_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Detalle Historia Clínica')),
                ('detalle_fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle_descripcion', models.TextField(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('historia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.historiaclinica')),
            ],
            options={
                'verbose_name_plural': 'Detalle Historia Clínica',
                'db_table': 'historia_clinica_detalle',
                'ordering': ['detalle_fecha'],
                'indexes': [models.Index(fields=['historia_id', 'detalle_fecha'], name='historia_cl_histori_f5562b_idx')],
                'constraints': [models.UniqueConstraint(fields=('historia_id', 'detalle_fecha'), name='unique_historia_detalle')],
                'unique_together': {('historia_id', 'detalle_fecha')},
            },
        ),
    ]
