# Generated by Django 5.1.1 on 2024-11-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagos',
            options={'verbose_name_plural': 'Pagos'},
        ),
        migrations.AddField(
            model_name='ingresopaciente',
            name='SalaEspera',
            field=models.ManyToManyField(blank=True, related_name='appointments', to='coreadmin.salaespera'),
        ),
        migrations.AlterField(
            model_name='estudios',
            name='app_total',
            field=models.IntegerField(default=0, verbose_name='Total de turnos'),
        ),
    ]
