# Generated by Django 5.1.1 on 2024-11-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreadmin', '0002_alter_pagos_options_ingresopaciente_salaespera_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultadolaboratorio',
            options={'ordering': ['resultado_fecha'], 'verbose_name_plural': 'Resultados'},
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='historia_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='HistoriaClinicaDetalle',
        ),
    ]
